<<<<<<< HEAD
<h1>Terms of Use</h1>
<p>You need to agree to the following Terms of Use in order to be provided the access to the core functions of FinVendor (the "Service").</p>
<h2>Access</h2>
<p>FinVendor grants Customer the non-exclusive and non-transferable right to access the Service and use the text, information, compilations of data, tables, graphs, charts or other materials on the Service ("Content"). Customer will not share its User ID with or provide access to unrelated third parties.</p>
<h2>Redistribution of Content</h2>
<p>Customer will not redistribute or otherwise use the Service for the benefit of third parties or to create a product for resale. Customer will not engage in or permit the automated, regular, and/or systematic collection or storage of Content. Customer may copy and print limited amounts of the Content for internal use only, and may copy or quote, on an occasional basis, limited amounts of the Content in external documents, only if: (1) such uses do not have the purpose or effect of eliminating the recipient's need to subscribe to the Service; (2) Customer does not use the data to create its own vendor database or otherwise state or imply that it is the source of the Content; and (3) the Content is attributed to FinVendor by means of a notice that substantially states "Source: FinVendor, © 2016, www.finvendor.com".</p>
<p>(Please contact FinVendor at <a href="mailto:support@finvedor.com" target="_top">support@finvedor.com</a> for more information on Redistribution)</p>
<h2>Proprietary Rights</h2>
<p>All intellectual property rights in or related to the Content are and will remain the exclusive property of FinVendor, whether or not specifically recognized or perfected under applicable law. If Customer creates or compiles content, data, or information identical or similar to any part of the Content (except as expressly permitted by this Agreement or by FinVendor in writing), Customer will not use or access the Content to do so. FINVENDOR will own all rights in any copy, translation, modification, adaptation or derivation of the Content. The Content, FINVENDOR's data collection methods, data structures and formats, and User I.D.s are the confidential information of FINVENDOR, to the extent they are nonpublic information. Customer will use reasonable care to protect and keep confidential and will not disclose such information or documents to third parties except as permitted by FINVENDOR.</p>
<h2>Disclaimer</h2>
=======
<h1>Terms of Use</h1>
<p>You need to agree to the following Terms of Use in order to be provided the access to the core functions of FinVendor (the "Service").</p>
<h2>Access</h2>
<p>FinVendor grants Customer the non-exclusive and non-transferable right to access the Service and use the text, information, compilations of data, tables, graphs, charts or other materials on the Service ("Content"). Customer will not share its User ID with or provide access to unrelated third parties.</p>
<h2>Redistribution of Content</h2>
<p>Customer will not redistribute or otherwise use the Service for the benefit of third parties or to create a product for resale. Customer will not engage in or permit the automated, regular, and/or systematic collection or storage of Content. Customer may copy and print limited amounts of the Content for internal use only, and may copy or quote, on an occasional basis, limited amounts of the Content in external documents, only if: (1) such uses do not have the purpose or effect of eliminating the recipient's need to subscribe to the Service; (2) Customer does not use the data to create its own vendor database or otherwise state or imply that it is the source of the Content; and (3) the Content is attributed to FinVendor by means of a notice that substantially states "Source: FinVendor, © 2016, www.finvendor.com".</p>
<p>(Please contact FinVendor at <a href="mailto:support@finvedor.com" target="_top">support@finvedor.com</a> for more information on Redistribution)</p>
<h2>Proprietary Rights</h2>
<p>All intellectual property rights in or related to the Content are and will remain the exclusive property of FinVendor, whether or not specifically recognized or perfected under applicable law. If Customer creates or compiles content, data, or information identical or similar to any part of the Content (except as expressly permitted by this Agreement or by FinVendor in writing), Customer will not use or access the Content to do so. FINVENDOR will own all rights in any copy, translation, modification, adaptation or derivation of the Content. The Content, FINVENDOR's data collection methods, data structures and formats, and User I.D.s are the confidential information of FINVENDOR, to the extent they are nonpublic information. Customer will use reasonable care to protect and keep confidential and will not disclose such information or documents to third parties except as permitted by FINVENDOR.</p>
<h2>Disclaimer</h2>
>>>>>>> origin/master
<p>THE CONTENT IS PROVIDED ON AN "AS IS" BASIS. The Content is obtained from sources that FINVENDOR considers to be reliable; however, no representation is made as to, and no responsibility, warranty or liability is accepted for, the accuracy or completeness of the information. The Content is subject to change at any time without notice. FINVENDOR MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE CONTENT UNLESS OTHERWISE SPECIFIED IN WRITING. TO THE FULL EXTENT PERMISSIBLE BY APPLICABLE LAW, FINVENDOR DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. FINVENDOR WILL NOT BE LIABLE FOR ANY DAMAGES OF ANY KIND ARISING FROM THE USE OF THE CONTENT INCLUDING, BUT NOT LIMITED TO DIRECT, INDIRECT, INCIDENTAL, PUNITIVE, AND CONSEQUENTIAL DAMAGES, UNLESS OTHERWISE SPECIFIED IN WRITING.</p>